[2023-11-09T17:58:39.617+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: query_scraper.collect_items_specifications manual__2023-11-09T17:19:26.510251+00:00 [queued]>
[2023-11-09T17:58:39.623+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: query_scraper.collect_items_specifications manual__2023-11-09T17:19:26.510251+00:00 [queued]>
[2023-11-09T17:58:39.623+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-09T17:58:39.637+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): collect_items_specifications> on 2023-11-09 17:19:26.510251+00:00
[2023-11-09T17:58:39.642+0000] {standard_task_runner.py:57} INFO - Started process 2277 to run task
[2023-11-09T17:58:39.644+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'query_scraper', 'collect_items_specifications', 'manual__2023-11-09T17:19:26.510251+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dag_definitions.py', '--cfg-path', '/tmp/tmp6tq_zzvk']
[2023-11-09T17:58:39.645+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask collect_items_specifications
[2023-11-09T17:58:39.673+0000] {task_command.py:415} INFO - Running <TaskInstance: query_scraper.collect_items_specifications manual__2023-11-09T17:19:26.510251+00:00 [running]> on host bc76e66ea169
[2023-11-09T17:58:39.714+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='query_scraper' AIRFLOW_CTX_TASK_ID='collect_items_specifications' AIRFLOW_CTX_EXECUTION_DATE='2023-11-09T17:19:26.510251+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-09T17:19:26.510251+00:00'
[2023-11-09T17:58:39.738+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/task_definitions.py", line 110, in scrape_specifications
    specs = self._scrape_specifications(df)
  File "/opt/airflow/dags/task_definitions.py", line 198, in _scrape_specifications
    scraper = ScrapeSpecifications()
  File "/opt/airflow/dags/task_definitions.py", line 14, in __init__
    self.domain = configs['domain']
KeyError: 'domain'
[2023-11-09T17:58:39.742+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=query_scraper, task_id=collect_items_specifications, execution_date=20231109T171926, start_date=20231109T175839, end_date=20231109T175839
[2023-11-09T17:58:39.748+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 21 for task collect_items_specifications ('domain'; 2277)
[2023-11-09T17:58:39.775+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-09T17:58:39.804+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
